# Dockerfile.prod (backend)
FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


FROM node:18-alpine AS final
WORKDIR /app
COPY --from=builder /app /app
RUN npm install --omit=dev

CMD ["node", "dist/main"]